/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2024-03-23 09:46:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class invoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!----Shashikala-------->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Invoice</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".container{\n");
      out.write("	border-radius: 5px;\n");
      out.write("	background-color: #000000;\n");
      out.write("	padding: 20px;\n");
      out.write("	width: 1200px;\n");
      out.write("	opacity: 0.8;\n");
      out.write("	margin-left : 50px;\n");
      out.write("	margin-top : 150px;\n");
      out.write("	color : white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a{\n");
      out.write("	text-decoration : none;\n");
      out.write("	color : yellow;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:hover{\n");
      out.write("	background-color : red;\n");
      out.write("}\n");
      out.write(".button-link1 {\n");
      out.write("	float: left;\n");
      out.write("	margin-top: 0px;\n");
      out.write("	margin-left : 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("	\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<font><strong>You Order Placed Successfully..!</strong></font>\n");
      out.write("	<div class=\"container\">\n");
      out.write("	");

	try{
		
	String driver = "com.mysql.jdbc.Driver";
	String url = "jdbc.mysql.//localhost:3306/gamingsite?autoReconnect=true&useSSL=false";
	String username = "root";
	String password = "";
	
	Class.forName(driver);
	
	}catch(Exception e){
		e.printStackTrace();
	}

	Connection connection = null;
	Statement statement = null;
	ResultSet resultset = null;

	
      out.write("\n");
      out.write("	<h2 class = \"user\" align=\"center\">\n");
      out.write("		<font><strong>Invoice</strong></font>\n");
      out.write("		<!-- <button type=\"button\">Click Me!</button> -->\n");
      out.write("	</h2>\n");
      out.write("	<table align=\"center\" cellpadding=\"15\" cellspacing=\"5\" border=\"1\">\n");
      out.write("		<tr>\n");
      out.write("		\n");
      out.write(" 		\n");
      out.write(" 	\n");
      out.write("\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td><b>User Name</b></td>\n");
      out.write("			<td><b>Game Name</b></td>\n");
      out.write("			<td><b>Payment</b></td>\n");
      out.write("			<td><b>Total Price</b></td>\n");
      out.write("						\n");
      out.write("		</tr>\n");
      out.write("		");

		

		try{ 
		connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/gamingsite?autoReconnect=true&useSSL=false" , "root" ,""); 
		statement = connection.createStatement(); 
		String sql = "SELECT * FROM cart"; 
		resultset = statement.executeQuery(sql); 
		while(resultset.next()){

		
      out.write("\n");
      out.write("\n");
      out.write("		<tr >\n");
      out.write("			<td>");
      out.print( resultset.getString("username") );
      out.write("</td>\n");
      out.write("			<td>");
      out.print( resultset.getString("gamename") );
      out.write("</td>\n");
      out.write("			<td>");
      out.print( resultset.getString("payement") );
      out.write("</td>\n");
      out.write("			<td>500.00</td>\n");
      out.write("			\n");
      out.write("		</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		");

		}
		
		}catch(Exception e)
		{ e.printStackTrace();}
		
      out.write("\n");
      out.write("	</table>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
